name: "renewable_energy_pipeline"
version: "1.0.0"

profile: "renewable_energy_pipeline"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"

models:
  renewable_energy_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  renewable_energy_pipeline:
    +schema: seed

vars:
  dbt_date:time_zone: "UTC"
  grid_avg_emission_factor: 0.45
